gym_hub/urls.py
from django.contrib import admin
from django.urls import path
from main.views import *
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('paymenthandler/', views.paymenthandler, name='paymenthandler'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetails/<int:id>', views.page_detail, name='pagedetails'),
    path('faqlist/', views.FAQ_List, name='faqlist'),
    path('enquiry/', views.Enquiry, name='enquiry'),
    path('gallery/', views.Gallery, name='gallery'),
    path('galleryimg/<int:id>', views.ImageGallery, name='galleryimg'),
    path('pricing/', views.Pricing, name='pricing'),
    path('checkout/<int:plan_id>', views.checkout, name='checkout'),
    path('checkoutsession/<int:plan_id>', views.checkout_session, name='checkoutsession'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_failure', views.pay_failure, name='pay_failure'),
    path("profile-detail/", views.profile_detail, name="profile-detail"),

]

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
# Create your models here.

class Banner(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length = 200)

#here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.alt_text
#here we are returning the image of the image in admin panel 
    def image_tag(self):
        return mark_safe('<img src ="%s" "width = "50" />' % (self.img.url))

class Service(models.Model):
    title = models.CharField(max_length =150)
    img = models.ImageField(upload_to="services/", null=True)
    details = models.TextField()

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.title
#here we are returning the image of the image in admin panel 
    def image_tag(self):
        return mark_safe('<img src ="%s" "width = "50" />' % (self.img.url))


class Pages(models.Model):
    title = models.CharField(max_length =150)
    details = models.TextField()

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.title
    

class FAQ(models.Model):
    ques = models.TextField()
    ans = models.TextField()

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.ques
    
class Enquiry(models.Model):
    full_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 50)
    details = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.full_name    


class Gallery(models.Model):
    title = models.CharField(max_length =150)
    img = models.ImageField(upload_to="Gallery/", null=True)
    details = models.TextField()

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.title
#here we are returning the image of the image in admin panel 
    def image_tag(self):
        return mark_safe('<img src ="%s" "width = "50" />' % (self.img.url))


class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete = models.CASCADE, null = True)
    alt_text = models.CharField(max_length =150)
    img = models.ImageField(upload_to="Gallery_mgs/", null=True)

    #here we are returning the name of the image in admin panel 
    def __str__(self):
        return self.alt_text
#here we are returning the image of the image in admin panel 
    def image_tag(self):
        return mark_safe('<img src ="%s" "width = "50" />' % (self.img.url))

class SubPlan(models.Model):
    title = models.CharField(max_length =150)
    max_member = models.IntegerField(null = True)
    price = models.IntegerField()

    def __str__(self):
        return self.title

class SubPlanFeature(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE)
    title = models.CharField(max_length =150)

    
    def __str__(self):
        return self.title


class PlanDiscount(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null =True)
    total_month = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self):
        return str(self.total_month)
    


class Subscriber(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE, null =True)
        mobile = models.CharField(max_length=20, null = True)
        address = models.TextField(null = True)
        img = models.ImageField(upload_to="profile/", null = True)

        def __str__(self):
           return str(self.user)
    

        def image_tag(self):
          return mark_safe('<img src ="%s" "width = "50" />' % (self.img.url))


class Subscription(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE, null =True)
        plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null =True)
        price = models.CharField(max_length= 50, null = True)
        
        class Meta:
            unique_together = ('user', 'plan')

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<title>{{page_name}}</title>
		{% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="" />
	</head>
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<!-- Required meta tags -->
			<meta charset="utf-8" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1"
			/>
			<!-- Bootstrap CSS -->
			<link href="assets/bootstrap.min.css" rel="stylesheet" />
			<!-- Bootstrap Icons -->
			<link
				rel="stylesheet"
				type="text/css"
				href="node_modules/bootstrap-icons/font/bootstrap-icons.css"
			/>
			<!-- jquery -->
			<script src="assets/jquery-3.6.0.min.js"></script>
			<title>Home - GYM HUB</title>
		</head>
		<body>
			<!-- Header -->
			<nav class="navbar navbar-expand-lg navbar-light bg-warning">
				<div class="container">
					<a class="navbar-brand" href="{% url 'home'%}"
						>GYM HUB</a
					>
					<button
						class="navbar-toggler"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navbarNav"
						aria-controls="navbarNav"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNav">
						<ul class="navbar-nav ms-auto">
							<li class="nav-item">
								<a
									class="nav-link"
									aria-current="page"
									href="{%url 'home'%}"
									>Home</a
								>
							</li>
							<li class="nav-item">
								<a
									class="nav-link"
									aria-current="page"
									href="{% url 'gallery'%}"
									>Gallery</a
								>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'pricing'%}"
									>Pricing</a
								>
							</li>
							<li class="nav-item">
								<a
									class="nav-link btn btn-sm btn-dark text-white"
									href="{% url 'enquiry' %}"
									>Enquiry</a
								>
							</li>
							<li class="nav-item dropdown">
								<a
									class="nav-link dropdown-toggle"
									href="#"
									id="navbarScrollingDropdown"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
									My Account
								</a>
								<ul
									class="dropdown-menu"
									aria-labelledby="navbarScrollingDropdown"
								>
									<li>
										<a
											class="dropdown-item"
											href="{% url 'register'%}"
											>Register</a
										>
									</li>
									<li>
										<a
											class="dropdown-item"
											href="{% url 'login' %}"
											>Login</a
										>
									</li>
									<li><hr class="dropdown-divider" /></li>
									<li>
										<a class="dropdown-item" href="{% url 'dashboard' %}"
											>DashBoard</a
										>
									</li>
									<li>
										<a
											class="dropdown-item"
											href="{% url 'logout'%}"
											>Logout</a
										>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<!-- Header End -->

			{%block start%} {% endblock %}

			<!--footer Start-->

			

			  <!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Gym Hub
          </h6>
          <p>
			Welcome to Gym Hub where fitness meets passion, and goals become achievements.
			 We are more than just a gym; we're a community dedicated to helping you unlock
			  your full potential and lead a healthier, happier life.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Quick Links
          </h6>
		  <p>
			<a href="{%url 'home' %}" class="text-reset">Home</a>
		  </p>
          <p>
            <a href="{%url 'pagedetails' 2 %}" class="text-reset">Privacy</a>
          </p>
          <p>
            <a href="{%url 'pagedetails' 3 %}" class="text-reset">Terms & Condition</a>
          </p>
          <p>
            <a href="{%url 'pagedetails' 1 %}" class="text-reset">About Us</a>
          </p>
        </div>
        <!-- Grid column -->

       

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> Amethi, Uttar Pradesh, India, 227405</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            md.sameer.edu@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +91 7617056679</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <footer class="bg-body-tertiary text-center text-lg-start">
	<!-- Copyright -->
	<div class="text-center bg-warning p-3">
	  © 2024 Copyright:
	  <p>
		  © 2024–2025 Gym Hub, Pvt. Ltd.
	  </p>	
				</div>
	<!-- Copyright -->
  </footer
  <!-- Copyright -->
</footer>
<!-- Footer -->

			<!--footer End-->
		</body>
	</html>
</html>

templates/checkout.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<main>
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading border-bottom pb-2">
			Checkout
		</h1>
		<table class="table table-bordered">
			<thead class="table-warning">
				<tr>
					<th>Plan</th>
					<th>Plan Detail</th>
					<th>Payment For</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<table class="table-bordered table">
							<tr>
								<th>Name</th>
								<td>{{plans.title}}</td>
							</tr>
							<tr>
								<th>Price</th>
								<td>{{plans.price}}</td>
							</tr>
							<tr>
								<th>Max Member</th>
								<td>30</td>
							</tr>
							<tr>
								<th>Already Registered</th>
								<td>15</td>
							</tr>
							<tr>
								<th>Balance Seats</th>
								<td>15</td>
							</tr>
						</table>
					</td>
					<td>
						<ul class="list-unstyled">
							{% for feature in plans.subplanfeature_set.all %}
							<li>- {{feature.title}}</li>
							{% endfor %}
						</ul>
					</td>
					<td>
						<table class="table table-bordered">
							{% for discount in plans.plandiscount_set.all %}
							<tr>
								<td>
									<input
										data-planprice="{{plans.price}}"
										data-discount="{{discount.total_discount}}"
										type="radio"
										id="validity1{{discount.id}}"
										name="validity"
										class="select-validity"
										value="{{discount.total_month}}"
									/>
								</td>
								<th>
									<label for="validity1{{discount.id}}"
										>{{discount.total_month}} Month</label
									>
								</th>
								<td>{{discount.total_discount}}%</td>
							</tr>
							{% endfor %}
						</table>
					</td>
				</tr>
			</tbody>
			<tfoot class="table-info">
				<tr>
					<td></td>
					<th>Total Amount</th>
					<td>
						<b>Rs.<span class="totalAmount">150</span></b>
					</td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td>
						<form method="post", action={%url 'checkoutsession' plans.id%}>
							{% csrf_token %}
						<input
							type="submit"
							value="Proceed to Payment"
							class="btn btn-primary"
						/>
					</form>
					</td>
				</tr>
			</tfoot>
		</table>
	</section>
	<!-- End -->
</main>
<!-- End -->

<script type="text/javascript">
	$(document).ready(function () {
		$(".select-validity").on("click", function () {
			var _planPrice = $(this).attr("data-planprice");
			var _planDisc = $(this).attr("data-discount");
			var _planValid = $(this).val();
			var _totalPrice = _planPrice * _planValid;
			if (_planDisc > 0) {
				var _discountedPrice = (_totalPrice * _planDisc) / 100;
				_discountedPrice = _totalPrice - _discountedPrice;
			} else {
				_discountedPrice = _totalPrice;
			}
			$(".totalAmount").text(_discountedPrice);
		});
	});
</script>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %} {%block start%}

<!-- Main Start -->
<main>
	<section class = "container my-4">
        <div class="row">

            <div class = "col-3 ">
                <div class = "list-group">
                    <a href="{% url 'profile-detail' %}" class = "list-group-item">Profile</a>
                    <a href="{% url 'edit-profile'%}" class = "list-group-item">Update Profile</a>
                </div>
            </div>
            
        </div>


    </section>    
</main>
<!-- End -->
{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %} {%block start%}

<!-- Main Start -->
<main>
	<section class="container my-4">
		<div class="row">
			<div class="col-3">
				<div class="list-group">
                    <a href="{% url 'profile-detail' %}" class = "list-group-item">Profile</a>

                    <a href="{% url 'edit-profile'%}" class = "list-group-item">Update Profile</a>
				</div>
			</div>
			<div class="col-9">
				<h3 class="mb-4 border-bottom pb-1">Update Profile</h3>
				{% if msg %}
				 <p class ="text-success">{{msg}}</p> 
				 {% endif %}
				<form action="" method="post">
					<table class="table table-border">
						{% csrf_token %} {{form.as_table}}
						<tr>
							<td colospan="2">
								<input type="submit" class="btn btn-warning" />
							</td>
						</tr>
					</table>
				</form>
			</div>
		</div>
	</section>
</main>
<!-- End -->
{% endblock %}

templates/enquiry.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<main>
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading border-bottom pb-2">
			Enquiry Form
		</h1>
		<div class="alert alert-success" role="alert"></div>
		<div class="row">
			<div class="col-md-6">
				<img src="/static/imgs/enquiry.jpg" class="img-fluid" />
			</div>
			<div class="col-md-6">
				{% if msg %}
				<div class="alert alert-success alert-dismissible" role="alert">
					{{msg}}
				</div>
				{% endif %}

				<form method="post" action="{% url 'enquiry' %}">
					{% csrf_token %}
					<table class="table table-bordered">
						{{form.as_table}}
						<tr>
							<td colspan="2">
								<input type="submit" class="btn btn-primary" />
							</td>
						</tr>
					</table>
				</form>
			</div>
		</div>
	</section>
	<!-- End -->
</main>
<!-- End -->
{% endblock %}

templates/faq.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<main>
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
		<div class="accordion" id="accordionExample">
			{% for ques in questions %}
			<div class="accordion-item">
				<h2 class="accordion-header" id="headingOne">
					<button
						class="accordion-button"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#collapseOne{{forloop.counter}} "
						aria-expanded="true"
						aria-controls="collapseOne"
					>
						{{ques.ques}}
					</button>
				</h2>
				<div
					id="collapseOne{{forloop.counter}}"
					class="accordion-collapse collapse"
					aria-labelledby="headingOne"
					data-bs-parent="#accordionExample"
				>
					<div class="accordion-body">{{ques.ans}}</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</section>
	<!-- End -->
</main>
<!-- End -->

{% endblock %}

templates/gallery.html
{% extends 'base.html' %} {%block start%}

<!-- Main Start -->
<main>
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading border-bottom pb-2">
			Gallery
		</h1>
		<div class="row">
			{% for gallery in gallerys %}
			<div class="col-md-4 mb-4">
				<div class="card">
					<img
						src="{{gallery.img.url}}"
						class="card-img-top"
						alt="..."
					/>
					<div class="card-body">
						<h5 class="card-title">{{gallery.title}}</h5>
						<p class="card-text">{{gallery.details}}</p>
						<a
							href="{%url 'galleryimg' gallery.id %}"
							class="btn btn-warning text-light bg-dark"
							>View All</a
						>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</section>
	<!-- End -->
</main>
<!-- End -->
{% endblock %}

templates/home.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<main>
	<!-- banner Start -->
	<div
		id="carouselExampleControls"
		class="carousel slide"
		data-bs-ride="carousel"
	>
		<div class="carousel-inner">
			{% for banner in banners %}
			<div
				class="carousel-item {%if forloop.counter == 1%} active {% endif %}"
			>
				<img
					src="{{banner.img.url}}"
					class="d-block w-100 h-100"
					alt="Slide 1"
				/>
			</div>
			{% endfor %}
		</div>
		<button
			class="carousel-control-prev"
			type="button"
			data-bs-target="#carouselExampleControls"
			data-bs-slide="prev"
		>
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button
			class="carousel-control-next"
			type="button"
			data-bs-target="#carouselExampleControls"
			data-bs-slide="next"
		>
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>
	<!-- End Banner -->
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading">Services</h1>
		<div class="row">
			{% for service in services %}
			<div class="col-md-4 mb-4">
				<div class="card ">
					<img
						src="{{service.img.url}}"
						class="card-img-top"
						alt="..."
					/>
					<div class="card-body">
						<h3 class="card-title">{{service.title}}</h3>
						<p class="card-text">{{service.details}}</p>
						<a href="#" class="btn btn-warning text-light bg-dark ">Read More</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</section>
	<!-- End -->

	<!-- Testimonials -->
	<section
		class="container-fluid bg-light py-4 mt-5 border-top border-bottom"
	>
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					{% for page in pagess %} {% if forloop.first %}
					<h1 class="mb-4 section-heading">{{page.title}}</h1>
					<p class="lh-base">{{page.details}}</p>
					<p>
						<a
							href="{%url 'pagedetails' 1 %}"
							class="btn btn-warning text-light bg-dark"
							>Read More</a
						>
					</p>
					{% endif %} {% endfor %}
				</div>
				<div class="col-md-6 offset-1">
					<h1 class="mb-4 section-heading">
						Gallery
						<a
							href="#"
							class="float-end btn btn-warning text-light bg-dark mt-2"
							>View All</a
						>
					</h1>
					<div class="gallery">
						{% for gimg in gimg %}
						<a data-lightbox="home-gallery" href="#"
							><img
								src="{{gimg.img.url}}"
								width="155"
								class="img-thumbnail"
								alt="...{{gimg.img.alt_text}}"
						/></a>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Testimonials -->
</main>
<!-- End -->

{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block start %} 

<section class="section-conten padding-y" style="min-height: 84vh">
	<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 450px; height:399px; margin-top: 100px">
		<div class="card-body">
			<h4 class="card-title mb-4">Log in</h4>
			<form method="POST">
				{% csrf_token %}
				<div class="form-group mb-4">
					<input
						name="username"
						class="form-control"
						placeholder="Email id"
						type="text"
					/>
				</div>
				<!-- form-group// -->
				<div class="form-group mb-4">
					<input
						name="password"
						class="form-control"
						placeholder="Password"
						type="password"
					/>
				</div>
				<!-- form-group// -->

				<div class="form-group mb-4">
					<label class=" custom-control custom-checkbox ml-5">
						<input
							type="checkbox"
							class="custom-control-input"
							checked=""
						/>
						<div class="custom-control-label">Remember</div>
					</label>
				</div>
				<!-- form-group form-check .// -->
				<div class="form-group mb-4">
					<button type="submit" class="btn btn-warning text-light bg-dark">
						Login
					</button>
				</div>
				<!-- form-group// -->
			</form>
		</div>
		<!-- card-body.// -->
	</div>
	<!-- card .// -->

	<p class="text-center mt-4">
		Don't have account? <a href="/account/register/">Sign up</a>
	</p>
	<br /><br />
	<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
</section>

{%endblock%}

templates/orderemail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Successfull</title>
</head>
<body>
    <h2>{{title}}/</h2>
    
</body>
</html>

templates/page.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<main>
	<!-- Services -->
	<section class="container my-4">
		<h1 class="text-center mb-4 section-heading">{{pages.title}}</h1>
		<p>{{pages.details}}</p>
	</section>
	<!-- End -->
</main>
<!-- End -->

{% endblock %}

templates/pricing.html
{% extends 'base.html' %} {%block start%}
<!-- Main Start -->
<section class="container my-4">
	<h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
	<main>
		<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
			{% for plan in plans %}
			<div class="col">
				<div class="card mb-4 rounded-3 shadow-sm">
					<div class="card-header py-3">
						<h4 class="my-0 fw-normal">{{plan.title}}</h4>
					</div>
					<div class="card-body">
						<h1 class="card-title pricing-card-title">
							Rs.{{plan.price}}<small class="text-muted fw-light"
								>/mo</small
							>
						</h1>
						<p class = "text-success">Maximum Capacity : {{plan.max_member}}</p>
						<ul class="list-unstyled mt-3 mb-4">
							{% for feature in plan.subplanfeature_set.all %}
							<li>{{feature.title}}</li>
							{% endfor %}
						</ul>
						{% if request.user.is_authenticated %}
						<a
							href="{%url 'checkout' plan.id%}"
							class="w-100 btn btn-lg btn-outline-warning text-dark"
							>Get started</a
						>
						{% else %}
						<a
							href="{% url 'login' %}"
							class="w-100 btn btn-lg btn btn-warning text-light bg-dark"
							>Get started</a
						>
						{% endif %}
					</div>
				</div>
				
			</div>

			{% endfor %}

			  <!-- Razorpay's Javascript code. -->
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
		</div>
	</main>
</section>
<!-- End -->
{% endblock %}

templates/profile_detail.html
{% extends 'base.html' %} {%block start%}

<!-- Main Start -->
<main>
	<section class="container my-4">
		<div class="row">
			<div class="col-3">
				<div class="list-group">
					<a href="{% url 'profile-detail' %}" class="list-group-item"
						>Profile</a
					>

					<a href="{% url 'edit-profile'%}" class="list-group-item"
						>Update Profile</a
					>
				</div>
			</div>
			<div class="col-9">
                <h3 class="mb-4 border-bottom pb-1">Profile</h3>
                <div class = "border pb-1 pt-3 ">
                    {% if request.user.is_authenticated %}
				<h5 class = "mb-4 border-bottom pb-1">First Name : {{user.first_name}}</h5>
				<h5 class = "mb-4 border-bottom pb-1">Last Name : {{user.last_name}}</h5>
				<h5 class = "mb-4 border-bottom pb-1">Email id : {{user.username}}</h5>
                {% endif %}
            </div>
			</div>
		</div>
	</section>
</main>
<!-- End -->
{% endblock %}

templates/register.html
{% extends 'base.html' %} {% block start %}

<section class="section-conten padding-y" style="min-height: 84vh">
	<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width: 500px;  margin-top: 100px">
		<div class="card-body">
			<h4 class="card-title mb-4">Register</h4>
			<form method="POST">
				{% csrf_token %}
				<div class="form-group mb-3">
					<input
						required
						name="first_name"
						class="form-control"
						placeholder="First Name"
						type="text"
					/>
				</div>
				<div class="form-group mb-3">
					<input
						required
						name="last_name"
						class="form-control"
						placeholder="Last Name"
						type="text"
					/>
				</div>
				<div class="form-group mb-3">
					<input
						required
						name="username"
						class="form-control"
						placeholder="Email id"
						type="text"
					/>
				</div>

				<!-- form-group// -->
				<div class="form-group mb-3 ">
					<input
						required
						name="password"
						class="form-control"
						placeholder="Password"
						type="password"
					/>
				</div>
				<!-- form-group// -->

				<div class="form-group mb-3 ">
					<label class="float-right custom-control custom-checkbox ">
						<input
							type="checkbox"
							class="custom-control-input"
							checked=""
						/>
						<div class="custom-control-label ">Remember</div>
					</label>
				</div>
				<!-- form-group form-check .// -->
				<div class="form-group">
					<button type="submit" class="btn btn-warning text-light bg-dark">
						Register
					</button>
				</div>
				<!-- form-group// -->
			</form>
		</div>
		<!-- card-body.// -->
	</div>
	<!-- card .// -->

	<p class="text-center mt-4">
		Already have account? <a href="/account/login/">Login</a>
	</p>
	<br /><br />
	<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
</section>

{%endblock%}